name: text_adventure_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  video_player: ^0.10.11+2
  shared_preferences: ^0.5.12+4
  bloc: ^6.1.1
  flutter_bloc: ^6.1.1
  get_it: ^5.0.3
  provider: ^4.3.2+3
  bloc_pattern: ^2.5.1
  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
  test: ^1.15.7
  bloc_test: ^7.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/localJson/adventure1.json
    - assets/localJson/felipeAdventure.json
    - assets/videos/desert.mp4
    - assets/images/camp.png
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
