name: text_adventure_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_player: ^0.10.11+2
  shared_preferences: ^0.5.8
  get_it: ^5.0.3
  bloc: ^6.1.1
  flutter_bloc: ^6.1.1 

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: 
  test: 

flutter:
  uses-material-design: true

  assets:
    - assets/localJson/adventure1.json
    - assets/localJson/felipeAdventure.json
    - assets/videos/desert.mp4
    - assets/images/camp.png
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
